# Generated by Django 2.0.13 on 2020-04-18 22:28

import blog.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to=blog.models.post_image_path),
            preserve_default=False,
        ),
    ]
